### ISSUE TITLE
Not compiling on Mac OS Sierra

### ISSUE THREAD

**Issue by sofifather** [OlegKunitsyn/libshout-java#10]
Have a trouble with mvn install:
Libshout/libshout-java/src/main/native/libshout.c:4:10: fatal error: 'shout/shout.h' file not found
#include <shout/shout.h>
         ^
1 error generated.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.395 s
[INFO] Finished at: 2016-12-28T15:14:27+02:00
[INFO] Final Memory: 7M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:native-maven-plugin:1.0-alpha-8:compile (javah) on project libshout-java: Error executing command line. Exit code:1 -> [Help 1]

**Comment by OlegKunitsyn** [comment]
Perhaps libshout-devel not installed (lack of shout/shout.h)

**Comment by sofifather** [comment]
after added 
                                                <source>
                                                    <directory>
                                                        /usr/local/Cellar/libshout/2.3.1/include
                                                    </directory>
                                                </source>
error illustrated above is gone,but have new one
/bin/sh -c cd /Users/useruser/Libshout/libshout-java && gcc -shared -lshout -o/Users/useruser/Libshout/libshout-java/target/libshout-java-2.2.2.jar target/objs/libshout.o -o /Users/useruser/Libshout/libshout-java/target/libshout-java.so
ld: library not found for -lshout
clang: error: linker command failed with exit code 1 (use -v to see invocation)
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 2.425s
Finished at: Tue Jan 17 00:42:30 EET 2017
Final Memory: 13M/155M
------------------------------------------------------------------------

**Comment by sofifather** [comment]
i was missing install xcode. all works fine after xcode-select --install
