### ISSUE TITLE
OpenJDK 10 support

### ISSUE THREAD

**Issue by denysobukh** [OlegKunitsyn/libshout-java#21]
According to [JEP 313](http://openjdk.java.net/jeps/313) Native-Header Generation Tool (javah) was removed from OpenJDK. There is no more possibility to compile libshout-java native classes.

**Comment by OlegKunitsyn** [comment]
Please try Java11 branch and report status

**Comment by NOBODY1213** [comment]
Using jdk-11.0.2.jdk returns:
> [ERROR] Failed to execute goal org.codehaus.mojo:native-maven-plugin:1.0-alpha-9:javah (javah) on project libshout-java: Error running javah command: Error executing command line. Exit code:2 -> [Help 1]

**Comment by OlegKunitsyn** [comment]
The branch Java11 does not contain code like this. Once again, please try Java11 branch and report status, then I merge that to master.

**Comment by OlegKunitsyn** [comment]
Java 11 supported, see readme
