### ISSUE TITLE
How can l use nonblocking mode?

### ISSUE THREAD

**Issue by saxingz** [OlegKunitsyn/libshout-java#23]
`Libshout icecast = new Libshout();
setxxx(xx);

###         icecast.setNonBlocking(true);

        icecast.open();`

the result is : 

java.io.IOException Socket is busy.

---------------------------------------------------------------------
if i use  `icecast.setNonBlocking(false);` 
then everything is ok.
---------------------------------------------------------------------

so can you tell me the right way to use nonblocking?

**Comment by OlegKunitsyn** [comment]
Please forward your question to libshout developers - https://github.com/xiph/Icecast-libshout
Libshout-java is only a binding to the binaries of libshout. Icecast2 can handle several parallel streams (threads) from libshout-java, as you can see in the demo.
