### ISSUE TITLE
symbol lookup error: libshout-java.so: undefined symbol: shout_init

### ISSUE THREAD

**Issue by Fornax96** [OlegKunitsyn/libshout-java#3]
Hello, I'm kinda new to Icecast and want to set up a simple automatic audio stream which plays music from my own music library.
The problem is that I can't seem to find any information about how to set up a project with this library. I copied the sample code from README.md, but as soon as the new Libshout object get initialized it throws this error:
    symbol lookup error: libshout-java.so: undefined symbol: shout_init
And the program exits with Java result 127.

I noticed that the readme file says that the library is ready for use on 32-bit systems, does that mean it does not work on my 64-bit Xubuntu PC?

**Comment by OlegKunitsyn** [comment]
Yes, you have to build it on your target system. See Compilation in README

**Comment by Fornax96** [comment]
That's exactly what I did. I cloned the repo and did "mvn install", then the library and shared object showed up in the "target" folder. Any idea what could be wrong?

**Comment by OlegKunitsyn** [comment]
I built on Ubuntu and got all tests failed. Debian and CentOS compiled well as described in README. No idea why, I can't fix that.

**Comment by Fornax96** [comment]
I'll try some more things, if I can get it to work I'll commit any extra steps I took to this repository.

**Comment by OlegKunitsyn** [comment]
Maybe you could try to build on Debian 64 and use "so" module under Ubuntu.

**Comment by Fornax96** [comment]
That worked, somehow. Now I'm even more curious as to why it didn't compile correctly under Ubuntu :confused: 

Thanks for the help

**Comment by Stevenator1** [comment]
Could somebody share their library .so file for the Debian 64 build?  I'm running into the same problem, but I don't have a debian system to build on.

**Comment by Fornax96** [comment]
This one is from my project: http://pixeldra.in/u/xy-aiS. Compiled it in a virtualbox machine a few months ago

**Comment by Stevenator1** [comment]
I'm still having problems getting it to work, still getting the same error as you did.  I include the libshout-java.jar file as a library of my eclipse project, and have the .so file in the target folder on the Ubuntu machine I'm trying to run it on.  Am I making any obvious mistakes?

**Comment by OlegKunitsyn** [comment]
Please find libshout-java.64.so in target folder, name it as libshout-java.so and try.

**Comment by Fornax96** [comment]
Also set the library path to the directory where the so is using this JVM option: "-Djava.library.path=lib/"

**Comment by Stevenator1** [comment]
Thank you both very much, that got it working!!
