### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by daslicht** [OlegKunitsyn/libshout-java#4]
Hello,
Do you know any solution to have individual song informations when using a dj mix as source file?
Maybe cue sheets ?
Is there a way to inject metadata somehow ?
Cheers Marc

**Comment by OlegKunitsyn** [comment]
See API on https://github.com/OlegKunitsyn/libshout-java/blob/master/src/main/java/com/gmail/kunicins/olegs/libshout/Libshout.java e.g. setMeta setInfo setDescription setGenre setName
Actually, not an issue. Closed.

**Comment by daslicht** [comment]
Thank you, i didnt knew how to contact you elsewhere, thats why i wrote here.
Is there also a way to set song specific metadata according to the current playing song ?
