### ISSUE TITLE
How to stream multi-mp3?

### ISSUE THREAD

**Issue by huynhphan89** [OlegKunitsyn/libshout-java#5]
I need to stream sequentially some mp3. I tried the example at homepage, but it didn't work.
Could you please write an example work with multi-mp3?
Thanks.

**Comment by OlegKunitsyn** [comment]
This example can stream mp3 files one by one, and used on myfm.at

**Comment by huynhphan89** [comment]
I found out the problem, my mp3 files didn't have same bitrate.
Thank for your support.
